In [3]:
import numpy as np
#Copies and view of objects

a = np.array([1,2,3,4])
b = a            #Assigning value of a to b;
print(b,"\n")
a[2] = 0         #Changing value of an element of a
print(a,'\n')  #Print a
print(b,'\n')  #print b: note the value change in b;
                #when assignment is performed, both point to same location
                

[1 2 3 4] 

[1 2 0 4] 

[1 2 0 4] 



In [4]:
a = np.array([1,2,3,4])
c = a[1:3]     #Slicing and assigning part of a to c
print(c,"\n")
a[1] = 999     #Changing value of an element of a
print(a,'\n')  #Print a
print(c,'\n')  #print c: note the value change in c;
                #Even when slicing is performed, 
                #both point to same location

[2 3] 

[  1 999   3   4] 

[999   3] 



In [5]:
#use Copy() for generating copies
a = np.array([1,2,3,4])
b = a.copy()    #Copy array a onto b
print(b,"\n")
a[2] = 0         #Changing value of an element of a
print(a,'\n')  #Print a
print(b,'\n')  #print b: in this case, b[2] is not changed as this is a copy

[1 2 3 4] 

[1 2 0 4] 

[1 2 3 4] 



In [6]:
#VECTORIZATION
#Concept for internal implementation of numpy
#vectorization is the absence of explicit loop
#loops are not ommitted they are implemented internally

#E.g Multiplying of elements of two arrays using a*b

#BROADCASTING
#Broadcasting allows an operator or function to act on two or more arrays
# to operate even if these arrays do nothave same shape. However there 
# are other rules
a = np.arange(16).reshape(4,4)
b = np.ones(4)
print(a,"\n")
print(b,"\n")
print(a+b)
#a+b got added even though they are of different dimension
# a=4*4 and b=1*4; so when a+b is done, b is made as 4*4 by replicating
# its rows

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[ 1.  1.  1.  1.] 

[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]
 [ 13.  14.  15.  16.]]


In [7]:
#Broadcasting with different hsapes
m = np.arange(6).reshape(3,1,2) #3*1*2 array
print(m,"\n")
n = np.arange(6).reshape(3,2,1) #3*2*1 array
print(n,"\n")
# visualize m in 3d
#           
#   0
#    1
#   2
#    3
#   4
#    5

#n  0 1
#   2 3
#   4 5


[[[0 1]]

 [[2 3]]

 [[4 5]]] 

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]] 



In [9]:
#For adding m and n both need augmentation of dimention
# m = 3*1*2 ->3*2*2
# n = 3*2*1 ->3*2*2
# m becomes
#         
#   0   0    Duplicate the 3*1*2 by duplicating 3*2 entries
#    1   1
#   2   2
#    3   3
#   4   4
#    5   5

# n become
# 
#   0   1     Duplicate the 3*2*1 by duplicating 3*2 entries
#    0   1
#   2   3
#    3   3
#   4   5
#    4   5

# m+n
#   
#  0    1
#   1    2
#  4    5
#   5    6
#  8    9
#   9    10
m+n #Output  matches

array([[[ 0,  1],
        [ 1,  2]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

In [10]:
#Broadcasting with different shapes
m = np.arange(6).reshape(2,3) #2*3 array
print(m,"\n")
n = np.arange(6).reshape(3,2) #3*2 array
print(n,"\n")
# print(m+n) # This doesn't work; Rule #1 where add a *1 to a missing
            # dimension; here no dimensions are misssing.

[[0 1 2]
 [3 4 5]] 

[[0 1]
 [2 3]
 [4 5]] 



In [17]:
#Structured Arrays
#Arrays can contain complex data atype, like struct
#Creat a simple array of structs as items. Use Dtype to specify comma
# separated specifiers to indicae elements that constitute a struct

structured = np.array([(1,"First",0.5,1+2j),(2,"Second",1.3,2-2j),
                       (3,"third",0.8,1+3j)],dtype=('i2,a6,f4,c8'))
structured

#dtypes:
#bytes = b1
# int = i1, i2,i4,i8
# unsigned ints = u1, u2, u4, u8
# floats f2,f4,f8
# complex: c8, c16
# fixed length string a<n>

array([(1, b'First', 0.5, (1+2j)),
       (2, b'Second', 1.2999999523162842, (2-2j)),
       (3, b'third', 0.800000011920929, (1+3j))], 
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [16]:
print()
print(structured[1],"\n")


(2, b'Second', 1.2999999523162842, (2-2j)) 



In [19]:
structured = np.array([(1,"First",0.5,1+2j),(2,"Second",1.3,2-2j),
                       (3,"third",0.8,1+3j)],dtype= 
                      ('int32,a6,float32,complex64')) #use explicit dtype
structured

array([(1, b'First', 0.5, (1+2j)),
       (2, b'Second', 1.2999999523162842, (2-2j)),
       (3, b'third', 0.800000011920929, (1+3j))], 
      dtype=[('f0', '<i4'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [25]:
structured = np.array([(1,"First",0.5,1+2j),(2,"Second",1.3,2-2j),
                       (3,"third",0.8,1+3j)],dtype= 
                      ('int32,a6,float32,complex64')) #use explicit dtype
print(structured['f0'], "\n")
#print(structured['<i4'], "\n") #fails
print(structured['f1'], "\n")
print(structured['f2'], "\n")
print(structured['f3'], "\n")



[1 2 3] 

[b'First' b'Second' b'third'] 

[ 0.5         1.29999995  0.80000001] 

[ 1.+2.j  2.-2.j  1.+3.j] 



In [10]:
#Reading and Writing Array Data on Files#
#load() and #save commands
data = np.arange(1,10).reshape(3,3)
np.save("saved_data",data)
loaded_data= np.load('saved_data.npy')
print(loaded_data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#Reading file with Tabular data
#reading csv file
data = np.genfromtxt("data.csv", delimiter = "," ,names =True)
    # data.csv has headings id, value1, value2, value3
print(data)
data #we get structured array where column heading has become names of field

[(1.0, 5.0, 7.0, 8.0) (2.0, 10.0, 14.0, 16.0) (3.0, 15.0, 21.0, 24.0)]


array([(1.0, 5.0, 7.0, 8.0), (2.0, 10.0, 14.0, 16.0),
       (3.0, 15.0, 21.0, 24.0)], 
      dtype=[('id', '<f8'), ('value2', '<f8'), ('value2_1', '<f8'), ('value3', '<f8')])

In [13]:
#reading csv file
data = np.genfromtxt("data2.csv", delimiter = "," ,names =True)
    # data.csv has headings id, value1, value2, value3
    # last entry in value3 is missing
print(data) #note nan is entered when there is missing data
data #we get structured array where column heading has become names of field

[(1.0, 5.0, 7.0, 8.0) (2.0, 10.0, 14.0, 16.0) (3.0, 15.0, 21.0, nan)]


array([(1.0, 5.0, 7.0, 8.0), (2.0, 10.0, 14.0, 16.0),
       (3.0, 15.0, 21.0, nan)], 
      dtype=[('id', '<f8'), ('value2', '<f8'), ('value2_1', '<f8'), ('value3', '<f8')])

In [15]:
print(data['id']) #retrieving values of id
print(data['value3']) #retrieving values of id

[ 1.  2.  3.]
[  8.  16.  nan]
