In [7]:
import numpy as np
#Joining Arrays
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)

print(np.vstack((a,b)),"\n") #Vertical stacking for Arrays
print(np.hstack((a,b)),"\n")


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]] 

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]] 



In [11]:
#Column_Stack() and row_Stack() used on 1-D arrays

a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.array([6,7,8])
print(np.column_stack((a,b,c)),"\n") #each array become the column
                                    #Note input it tuple
print(np.row_stack((a,b,c))) #each array becomes the row

[[0 3 6]
 [1 4 7]
 [2 5 8]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#Splitting arrays:
a = np.arange(16).reshape(4,4)
print(a,"\n")
[b,c] = np.hsplit(a,2) #split a horizontally into two segments
print(b,"\n")
print(c,"\n")

[b,c] = np.vsplit(a,2) #split a vertically into two segments
print(b,"\n")
print(c,"\n")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]] 



In [14]:
a = np.arange(9).reshape(3,3)
print(a,"\n")
[b,c,d] = np.hsplit(a,3) #split a horizontally into three segments
print(b,"\n")
print(c,"\n")
print(d,"\n")

[b,c,d] = np.vsplit(a,3) #split a vertically into three segments
print(b,"\n")
print(c,"\n")
print(d,"\n")

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0]
 [3]
 [6]] 

[[1]
 [4]
 [7]] 

[[2]
 [5]
 [8]] 

[[0 1 2]] 

[[3 4 5]] 

[[6 7 8]] 



In [17]:
#Split function allows to split into nonsymetrical arrays
a = np.arange(16).reshape(4,4)

[a1,a2,a3] = np.split(a, [1,2], axis = 1)
        # axis = 1 -> indexes indicate columnwise
print(a1,"\n")
print(a2,"\n")
print(a3,"\n")

[[ 0]
 [ 4]
 [ 8]
 [12]] 

[[ 1]
 [ 5]
 [ 9]
 [13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 



In [18]:
#Split function allows to split into nonsymetrical arrays
a = np.arange(16).reshape(4,4)

[a1,a2,a3] = np.split(a, [1,3], axis = 1)
        # axis = 1 -> indexes indicate columnwise
print(a1,"\n")
print(a2,"\n")
print(a3,"\n")

[[ 0]
 [ 4]
 [ 8]
 [12]] 

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]] 

[[ 3]
 [ 7]
 [11]
 [15]] 



In [19]:
#Split function allows to split into nonsymetrical arrays
a = np.arange(25).reshape(5,5)

[a1,a2,a3] = np.split(a, [2,4], axis = 1)
        # axis = 1 -> indexes indicate columnwise
print(a1,"\n")
print(a2,"\n")
print(a3,"\n")

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]] 

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]] 

[[ 4]
 [ 9]
 [14]
 [19]
 [24]] 

