In [2]:
import numpy as np
a = np.arange(4)
print(a) #Print array
print()
print(a+4) #Addition
print()
print(a*2) #Multiplication
print()
print(a+a+a) #array addition

[0 1 2 3]

[4 5 6 7]

[0 2 4 6]

[0 3 6 9]


In [6]:
a = np.arange(4)
b = np.ones((1,4))
print(a*np.sin(b)) #adding sin of a value

array([[ 0.        ,  0.84147098,  1.68294197,  2.52441295]])

In [7]:
a = np.arange(4)
b = np.arange(4,8)
print(a*np.sqrt(b)) #square root

[ 0.          2.23606798  4.89897949  7.93725393]


In [10]:
#Multi dimensional operations
a = np.arange(0,9).reshape(3,3)
b = np.ones((3,3))
print(a)
print()
print(b)
print()
print(a*b) #per element multiplication
print()
print(np.dot(a,b)) #Matrix multiplication

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]

[[  3.   3.   3.]
 [ 12.  12.  12.]
 [ 21.  21.  21.]]


In [4]:
#universal function
#universal funtion is a function operating on an array element yb element
#e.g sqrt, log, sin etc

a = np.array([[1,4,9,16,25]])
print(np.sqrt(a))
print(np.log(a))
print(np.sin(a))

[[ 1.  2.  3.  4.  5.]]
[[ 0.          1.38629436  2.19722458  2.77258872  3.21887582]]
[[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]]


In [6]:
#Aggregate functions
#Acts on arrays and produces a single result
a = np.array([[1,2,4,5,5]])
print(a.sum())
print(a.min())
print(a.max())
print(a.std())

17
1
5
1.62480768093


In [4]:
#Indexing; Slicing; Iterating
a = np.arange(10,16) #Note 16 is not included
print(a)
print(a[0]) #1st element
print(a[[1,2]]) #2nd and 3rd element
print()
print(a[-1]) #Last element
print(a[2:4]) #3rd to 5th element
print(a[-3:-1]) # last to 3rd last lement
print(a[0:5:2])
print(a[0:0:2])

[10 11 12 13 14 15]
10
[11 12]

15
[12 13]
[13 14]
[10 12 14]
[]


In [22]:
a = np.arange(1,10).reshape(3,3)
print(a)
print()

print(a[0,0])
print(a[2,2])
print(a[0,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

1
9
3


In [7]:
a = np.arange(1,10).reshape(3,3)
print(a)
print()
print(a[0,:]) # 1st row
print()
print(a[:,0]) # 1st column

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]

[1 4 7]


In [11]:
#Sub matrices:
a = np.arange(1,10).reshape(3,3)
print(a)
print()
b=a[0:2,0:2] #copy 1st and 2nd row and column
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]]


In [13]:
a = np.arange(1,10).reshape(3,3)
print(a)
print()
b=a[[0,2],0:2] #copy 1st and 3rd row; and 1st and 2nd column
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [7 8]]


In [15]:
#iterating an array
a = np.arange(1,10).reshape(3,3)
print()
for i in a:
    print(i) # each i is a row/axis
    print()


[1 2 3]

[4 5 6]

[7 8 9]



In [3]:
#per element loop
a = np.arange(1,5).reshape(2,2)
print()
for i in a.flat:
    print(i)


1
2
3
4


In [6]:
#Alternative to loop; applying a function to row or column
a = np.arange(1,10).reshape(3,3)
print(a)
print()
print(np.apply_along_axis(np.mean, axis =0, arr = a)) #columnwise mean
print()
print(np.apply_along_axis(np.mean, axis =1, arr = a)) #Rowwise mean

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[ 4.  5.  6.]

[ 2.  5.  8.]


In [14]:
#apply_along_axis is more powerful because you can define your own function
print(a)
print()
def halve(x):
    return x/2
def tsum(x):
    return sum(x)
print(np.apply_along_axis(halve, axis =0, arr = a), "\n") #halves all elments
print(np.apply_along_axis(sum, axis =0, arr = a),"\n") #columnwise sum
print(np.apply_along_axis(sum, axis =1, arr = a),"\n") #rowwise sum

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 0.5  1.   1.5]
 [ 2.   2.5  3. ]
 [ 3.5  4.   4.5]] 

[12 15 18] 

[ 6 15 24] n


In [15]:
#Conditional and Boolean Arrays

a = np.random.random((4,4))
print(a,"\n")
print(a<0.5,"\n") #boolean array giving which values satisfy the condition
print(a[a<0.5],"\n") #gives a list of entries with values larger than 0.5

[[ 0.32251607  0.09921411  0.36983647  0.39000434]
 [ 0.86731344  0.13530269  0.50416858  0.02193761]
 [ 0.91047874  0.62474231  0.93162511  0.81913449]
 [ 0.60179465  0.16902447  0.62368365  0.14725971]] 

[[ True  True  True  True]
 [False  True False  True]
 [False False False False]
 [False  True False  True]] 

[ 0.32251607  0.09921411  0.36983647  0.39000434  0.13530269  0.02193761
  0.16902447  0.14725971] 



In [21]:
#Shape Manipulation
a = np.random.random(12)
print(a,"\n")
#Reshape creates a new array with required shape
print(a.reshape(3,4),"\n") #new array with the shape
print(a,"\n") #shape of a is unchanged

#assign values a tuple for reshaping the existing array
a.shape = (3,4)
print(a)

[ 0.4590292   0.39368942  0.00524018  0.47488693  0.50958411  0.88985135
  0.94296341  0.05411268  0.23540655  0.66608822  0.46731678  0.32016034] 

[[ 0.4590292   0.39368942  0.00524018  0.47488693]
 [ 0.50958411  0.88985135  0.94296341  0.05411268]
 [ 0.23540655  0.66608822  0.46731678  0.32016034]] 

[ 0.4590292   0.39368942  0.00524018  0.47488693  0.50958411  0.88985135
  0.94296341  0.05411268  0.23540655  0.66608822  0.46731678  0.32016034] 

[[ 0.4590292   0.39368942  0.00524018  0.47488693]
 [ 0.50958411  0.88985135  0.94296341  0.05411268]
 [ 0.23540655  0.66608822  0.46731678  0.32016034]]


In [24]:
#ravel converts a 2-D array to 1-D array
a = np.arange(1,10).reshape(3,3)
b = a
print(a,"\n")
a = a.ravel()
print(a,"\n")
b.shape = (9) #shaping to a single dimension does same as ravel()
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9] 

[1 2 3 4 5 6 7 8 9]


In [25]:
#Transpose
a = np.arange(1,10).reshape(3,3)
print(a,"\n")
a.transpose()

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])