In [1]:
import numpy as np
#Copies and view of objects

a = np.array([1,2,3,4])
b = a            #Assigning value of a to b;
print(b,"\n")
a[2] = 0         #Changing value of an element of a
print(a,'\n')  #Print a
print(b,'\n')  #print b: note the value change in b;
                #when assignment is performed, both point to same location
                

[1 2 3 4] 

[1 2 0 4] 

[1 2 0 4] 



In [2]:
a = np.array([1,2,3,4])
c = a[1:3]     #Slicing and assigning part of a to c
print(c,"\n")
a[1] = 999     #Changing value of an element of a
print(a,'\n')  #Print a
print(c,'\n')  #print c: note the value change in c;
                #Even when slicing is performed, 
                #both point to same location

[2 3] 

[  1 999   3   4] 

[999   3] 



In [3]:
#use Copy() for generating copies
a = np.array([1,2,3,4])
b = a.copy()    #Copy array a onto b
print(b,"\n")
a[2] = 0         #Changing value of an element of a
print(a,'\n')  #Print a
print(b,'\n')  #print b: in this case, b[2] is not changed as this is a copy

[1 2 3 4] 

[1 2 0 4] 

[1 2 3 4] 



In [5]:
#VECTORIZATION
#Concept for internal implementation of numpy
#vectorization is the absence of explicit loop
#loops are not ommitted they are implemented internally

#E.g Multiplying of elements of two arrays using a*b

#BROADCASTING
#Broadcasting allows an operator or function to act on two or more arrays
# to operate even if these arrays do nothave same shape. However there 
# are other rules
a = np.arange(16).reshape(4,4)
b = np.ones(4)
print(a,"\n")
print(b,"\n")
print(a+b)
#a+b got added even though they are of different dimension
# a=4*4 and b=1*4; so when a+b is done, b is made as 4*4 by replicating
# its rows

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[ 1.  1.  1.  1.] 

[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]
 [ 13.  14.  15.  16.]]


In [7]:
#Broadcasting with different hsapes
m = np.arange(6).reshape(3,1,2) #3*1*2 array
print(m,"\n")
n = np.arange(6).reshape(3,2,1) #3*2*1 array
print(n,"\n")
# visualize m in 3d
#    1       
#   0
#    3
#   2
#    5
#   4

#n  0 1
#   2 3
#   4 5


[[[0 1]]

 [[2 3]]

 [[4 5]]] 

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]] 



In [8]:
#For adding m and n both need augmentation of dimention


In [9]:
#Broadcasting with different shapes
m = np.arange(6).reshape(2,3) #2*3 array
print(m,"\n")
n = np.arange(6).reshape(3,2) #3*2 array
print(n,"\n")
# print(m+n) # This doesn't work

[[0 1 2]
 [3 4 5]] 

[[0 1]
 [2 3]
 [4 5]] 



ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 