In [3]:
import numpy as np
a = np.arange(4)
print(a) #Print array
print()
print(a+4) #Addition
print()
print(a*2) #Multiplication
print()
print(a+a+a) #array addition

[0 1 2 3]

[4 5 6 7]

[0 2 4 6]

[0 3 6 9]


In [6]:
a = np.arange(4)
b = np.ones((1,4))
print(a*np.sin(b)) #adding sin of a value

array([[ 0.        ,  0.84147098,  1.68294197,  2.52441295]])

In [7]:
a = np.arange(4)
b = np.arange(4,8)
print(a*np.sqrt(b)) #square root

[ 0.          2.23606798  4.89897949  7.93725393]


In [10]:
#Multi dimensional operations
a = np.arange(0,9).reshape(3,3)
b = np.ones((3,3))
print(a)
print()
print(b)
print()
print(a*b) #per element multiplication
print()
print(np.dot(a,b)) #Matrix multiplication

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]

[[  3.   3.   3.]
 [ 12.  12.  12.]
 [ 21.  21.  21.]]


In [ ]:
#universal function
#universal funtion is a function operating on an array element yb element
#e.g sqrt, log, sin etc

a = np.array([[1,4,9,16,25]])
print(np.sqrt(a))
print(np.log(a))
print(np)