In [3]:
import numpy as np
a = np.arange(4)
print(a) #Print array
print()
print(a+4) #Addition
print()
print(a*2) #Multiplication
print()
print(a+a+a) #array addition

[0 1 2 3]

[4 5 6 7]

[0 2 4 6]

[0 3 6 9]


In [6]:
a = np.arange(4)
b = np.ones((1,4))
print(a*np.sin(b)) #adding sin of a value

array([[ 0.        ,  0.84147098,  1.68294197,  2.52441295]])

In [7]:
a = np.arange(4)
b = np.arange(4,8)
print(a*np.sqrt(b)) #square root

[ 0.          2.23606798  4.89897949  7.93725393]


In [10]:
#Multi dimensional operations
a = np.arange(0,9).reshape(3,3)
b = np.ones((3,3))
print(a)
print()
print(b)
print()
print(a*b) #per element multiplication
print()
print(np.dot(a,b)) #Matrix multiplication

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]

[[  3.   3.   3.]
 [ 12.  12.  12.]
 [ 21.  21.  21.]]


In [4]:
#universal function
#universal funtion is a function operating on an array element yb element
#e.g sqrt, log, sin etc

a = np.array([[1,4,9,16,25]])
print(np.sqrt(a))
print(np.log(a))
print(np.sin(a))

[[ 1.  2.  3.  4.  5.]]
[[ 0.          1.38629436  2.19722458  2.77258872  3.21887582]]
[[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]]


In [6]:
#Aggregate functions
#Acts on arrays and produces a single result
a = np.array([[1,2,4,5,5]])
print(a.sum())
print(a.min())
print(a.max())
print(a.std())

17
1
5
1.62480768093


In [25]:
#Indexing; Slicing; Iterating
a = np.arange(10,16) #Note 16 is not included
print(a)
print(a[0]) #1st element
print(a[[1,2]]) #2nd and 3rd element
print()
print(a[-1]) #Last element
print(a[2:4]) #3rd to 5th element
print(a[-3:-1]) # last to 3rd last lement
print(a[0:5:2])
print(A[0:0:2])

[10 11 12 13 14 15]
10
[11 12]

15
[12 13]
[13 14]
[10 12 14]


In [22]:
a = np.arange(1,10).reshape(3,3)
print(a)
print()

print(a[0,0])
print(a[2,2])
print(a[0,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

1
9
3


In [7]:
a = np.arange(1,10).reshape(3,3)
print(a)
print()
print(a[0,:]) # 1st row
print()
print(a[:,0]) # 1st column

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]

[1 4 7]


In [11]:
#Sub matrices:
a = np.arange(1,10).reshape(3,3)
print(a)
print()
b=a[0:2,0:2] #copy 1st and 2nd row and column
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]]


In [13]:
a = np.arange(1,10).reshape(3,3)
print(a)
print()
b=a[[0,2],0:2] #copy 1st and 3rd row; and 1st and 2nd column
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [7 8]]


In [15]:
#iterating an array
a = np.arange(1,10).reshape(3,3)
print()
for i in a:
    print(i) # 
    print()


[1 2 3]

[4 5 6]

[7 8 9]

