In [5]:
import numpy as np
import pandas as pd

n_array = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print("Array: \n",n_array)
print("Dimension of array:", n_array.ndim)
print("Shape of the array: ", n_array.shape)
print("Size of the array: ",n_array.size)
print("Array type:", n_array.dtype)

Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Dimension of array: 2
Shape of the array:  (3, 4)
Size of the array:  12
Array type: int64


In [7]:
#Panel
#Panel handles 3D data structure:

d ={"item1": pd.DataFrame(np.random.randn(4,3)),
    "item2": pd.DataFrame(np.random.randn(4,2))}
pd.Panel(d)

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 4 (major_axis) x 3 (minor_axis)
Items axis: item1 to item2
Major_axis axis: 0 to 3
Minor_axis axis: 0 to 2